import { getSupabase } from './client';
import { recalculateWeakness } from '../adaptive/weaknessStatus';
import { ADAPTIVE_THRESHOLDS } from '../adaptive/thresholds';
import type {
  CoreCategory,
  Weakness,
} from '../types';

export async function getWeaknessesForLearner(
  learnerId: string
): Promise<Weakness[]> {
  const { data, error } = await getSupabase()
    .from('weaknesses')
    .select('*')
    .eq('learner_id', learnerId);

  if (error) {
    throw new Error(
      `getWeaknessesForLearner failed: ${error.message}`
    );
  }

  return (data ?? []) as Weakness[];
}

async function getOrInitWeakness(
  learnerId: string,
  category: CoreCategory
): Promise<Weakness> {
  const { data, error } = await getSupabase()
    .from('weaknesses')
    .select('*')
    .eq('learner_id', learnerId)
    .eq('category', category)
    .maybeSingle();

  if (error) {
    throw new Error(
      `getOrInitWeakness failed: ${error.message}`
    );
  }

  if (data) {
    return data as Weakness;
  }

  return {
    id: '',
    learner_id: learnerId,
    category,
    error_count: 0,
    diagnostic_error_count: 0,
    practice_error_count: 0,
    attempt_count: 0,
    relevant_question_count: 0,
    correct_count: 0,
    accuracy: 0,
    status: 'potential',
    priority: 'medium',
    last_detected: null,
    created_at: '',
    updated_at: '',
  };
}

async function upsertRow(
  row: Weakness
): Promise<Weakness> {
  // Build only the columns that are writable.
  //
  // Do not send:
  // - error_count: generated by Postgres
  // - created_at: generated by Postgres
  //
  // updated_at is refreshed here on every write.

  const writableRow = {
    learner_id: row.learner_id,
    category: row.category,

    diagnostic_error_count:
      row.diagnostic_error_count,

    practice_error_count:
      row.practice_error_count,

    attempt_count:
      row.attempt_count,

    relevant_question_count:
      row.relevant_question_count,

    correct_count:
      row.correct_count,

    accuracy:
      row.accuracy,

    status:
      row.status,

    priority:
      row.priority,

    last_detected:
      row.last_detected,

    ...(row.id
      ? {
          id: row.id,
        }
      : {}),

    updated_at:
      new Date().toISOString(),
  };

  const { data, error } = await getSupabase()
    .from('weaknesses')
    .upsert(
      writableRow,
      {
        onConflict:
          'learner_id,category',
      }
    )
    .select()
    .single();

  if (error) {
    throw new Error(
      `upsertRow(weaknesses) failed: ${error.message}`
    );
  }

  return data as Weakness;
}

/**
 * Record evidence from a diagnostic submission.
 *
 * One diagnostic submission counts as one evidence event,
 * regardless of how many individual errors it contains.
 */
export async function recordDiagnosticEvidence(
  learnerId: string,
  category: CoreCategory,
  newErrorCount: number
): Promise<Weakness> {
  const current =
    await getOrInitWeakness(
      learnerId,
      category
    );

  const updated = {
    ...current,

    diagnostic_error_count:
      current.diagnostic_error_count +
      newErrorCount,

    attempt_count:
      current.attempt_count + 1,

    last_detected:
      new Date().toISOString(),
  };

  const derived =
    recalculateWeakness(updated);

  return upsertRow({
    ...updated,
    ...derived,
  });
}

/**
 * Record evidence from normal adaptive practice.
 *
 * Wrong answers become practice-error evidence, while the
 * exercise totals also update cumulative accuracy.
 */
export async function recordPracticeEvidence(
  learnerId: string,
  category: CoreCategory,
  result: {
    totalQuestions: number;
    correctCount: number;
  }
): Promise<Weakness> {
  const current =
    await getOrInitWeakness(
      learnerId,
      category
    );

  const incorrectCount =
    result.totalQuestions -
    result.correctCount;

  const updated = {
    ...current,

    practice_error_count:
      current.practice_error_count +
      incorrectCount,

    attempt_count:
      current.attempt_count + 1,

    relevant_question_count:
      current.relevant_question_count +
      result.totalQuestions,

    correct_count:
      current.correct_count +
      result.correctCount,

    last_detected:
      new Date().toISOString(),
  };

  const derived =
    recalculateWeakness(updated);

  return upsertRow({
    ...updated,
    ...derived,
  });
}

/**
 * Reactivate a previously mastered weakness after maintenance
 * decline has been CONFIRMED.
 *
 * Important:
 *
 * Maintenance reviews are stored separately while we are still
 * determining whether the decline is real.
 *
 * We call this function only after the required number of
 * consecutive weak maintenance reviews has been reached.
 *
 * At that point, the confirmed maintenance performance becomes
 * relevant adaptive evidence.
 *
 * We do NOT add maintenance mistakes to practice_error_count,
 * because maintenance has its own evidence source/history.
 *
 * The original diagnostic/practice history is preserved.
 */
export async function reactivateWeaknessFromMaintenance(
  learnerId: string,
  category: CoreCategory,
  evidence: {
    totalQuestions: number;
    correctCount: number;
    reviewCount: number;
  }
): Promise<Weakness> {
  if (evidence.totalQuestions <= 0) {
    throw new Error(
      'reactivateWeaknessFromMaintenance: totalQuestions must be greater than 0'
    );
  }

  if (
    evidence.correctCount < 0 ||
    evidence.correctCount >
      evidence.totalQuestions
  ) {
    throw new Error(
      'reactivateWeaknessFromMaintenance: correctCount must be between 0 and totalQuestions'
    );
  }

  if (evidence.reviewCount <= 0) {
    throw new Error(
      'reactivateWeaknessFromMaintenance: reviewCount must be greater than 0'
    );
  }

  const current =
    await getOrInitWeakness(
      learnerId,
      category
    );

  const updated = {
    ...current,

    // Each completed maintenance review is one new
    // evidence event.
    attempt_count:
      current.attempt_count +
      evidence.reviewCount,

    // Confirmed maintenance questions now contribute to
    // cumulative exercise-performance evidence.
    relevant_question_count:
      current.relevant_question_count +
      evidence.totalQuestions,

    correct_count:
      current.correct_count +
      evidence.correctCount,

    last_detected:
      new Date().toISOString(),
  };

  const derived =
    recalculateWeakness(updated);

  const maintenanceAccuracy =
    evidence.correctCount /
    evidence.totalQuestions;

  /*
   * Recent confirmed decline must be allowed to override
   * historical mastery.
   *
   * Example:
   *
   * A learner may historically have 95% accuracy from many
   * exercises, yet score below 70% in two consecutive current
   * maintenance reviews.
   *
   * If we looked only at lifetime accuracy, the old large sample
   * could hide the learner's current decline.
   *
   * Therefore confirmed recent decline explicitly reactivates
   * the category.
   */
  const reactivatedStatus: Weakness['status'] =
    'needs_practice';

  const reactivatedPriority: Weakness['priority'] =
    maintenanceAccuracy <
    ADAPTIVE_THRESHOLDS
      .LOW_PERFORMANCE_ACCURACY
      ? 'high'
      : 'medium';

  return upsertRow({
    ...updated,
    ...derived,

    status:
      reactivatedStatus,

    priority:
      reactivatedPriority,
  });
}