-- رِحلة V1 schema
-- Locked clarifications applied:
--  - attempts = diagnostic (free-text) submissions ONLY
--  - practice_sessions = one batch of 5 generated exercises + its evaluation
--  - exercise_attempts = individual answers within a practice_session
--  - CHECK constraints, FKs, indexes, and unique(learner_id, category)
--    on weaknesses are kept as approved.

create extension if not exists "uuid-ossp";

create table if not exists learners (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  self_reported_level text not null check (self_reported_level in
    ('Beginner','Elementary','Intermediate','Upper Intermediate','Advanced')),
  learning_goal text not null check (learning_goal in
    ('Speaking','Writing','Reading','Understanding Arabic','General Arabic')),
  observed_level text not null default 'Beginner' check (observed_level in
    ('Beginner','Elementary','Intermediate','Upper Intermediate','Advanced')),
  strengths jsonb not null default '[]',
  current_focus text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Diagnostic free-text submissions ONLY (spec §6). Each row is one
-- "evidence event" of the kind counted by weaknesses.attempt_count.
create table if not exists attempts (
  id uuid primary key default uuid_generate_v4(),
  learner_id uuid not null references learners(id) on delete cascade,
  input_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists errors (
  id uuid primary key default uuid_generate_v4(),
  learner_id uuid not null references learners(id) on delete cascade,
  attempt_id uuid not null references attempts(id) on delete cascade,
  category text not null check (category in
    ('حروف الجر','التذكير والتأنيث','المفرد والجمع','Other')),
  original_text text not null,
  correction text not null,
  explanation_ar text not null,
  explanation_en text not null,
  confidence numeric not null check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now()
);

create table if not exists weaknesses (
  id uuid primary key default uuid_generate_v4(),
  learner_id uuid not null references learners(id) on delete cascade,
  category text not null check (category in
    ('حروف الجر','التذكير والتأنيث','المفرد والجمع')),
  error_count int not null default 0,
  attempt_count int not null default 0,
  relevant_question_count int not null default 0,
  correct_count int not null default 0,
  accuracy numeric not null default 0 check (accuracy >= 0 and accuracy <= 1),
  status text not null default 'potential' check (status in
    ('potential','needs_practice','improving','mastered')),
  priority text not null default 'medium' check (priority in ('high','medium','low')),
  last_detected timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (learner_id, category)
);

-- One batch of exactly 5 exercises generated by one adaptive
-- decision, plus that batch's evaluation summary. Distinguishes a
-- "practice session" (this table) from a "diagnostic attempt"
-- (attempts table), per locked clarification #6.
create table if not exists practice_sessions (
  id uuid primary key default uuid_generate_v4(),
  learner_id uuid not null references learners(id) on delete cascade,
  weakness_category text not null check (weakness_category in
    ('حروف الجر','التذكير والتأنيث','المفرد والجمع')),
  difficulty text not null check (difficulty in ('easy','moderate','hard','transfer')),
  score numeric check (score is null or (score >= 0 and score <= 1)),
  accuracy_before numeric,
  accuracy_after numeric,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists exercises (
  id uuid primary key default uuid_generate_v4(),
  learner_id uuid not null references learners(id) on delete cascade,
  practice_session_id uuid not null references practice_sessions(id) on delete cascade,
  weakness_category text not null check (weakness_category in
    ('حروف الجر','التذكير والتأنيث','المفرد والجمع')),
  difficulty text not null check (difficulty in ('easy','moderate','hard','transfer')),
  exercise_type text not null check (exercise_type in
    ('multiple_choice','correction','fill_in_blank','free_production')),
  instruction_ar text not null,
  question text not null,
  options jsonb,
  correct_answer text not null,
  explanation_ar text not null,
  created_at timestamptz not null default now()
);

create table if not exists exercise_attempts (
  id uuid primary key default uuid_generate_v4(),
  exercise_id uuid not null references exercises(id) on delete cascade,
  learner_id uuid not null references learners(id) on delete cascade,
  answer text not null,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_errors_learner_category on errors (learner_id, category);
create index if not exists idx_weaknesses_learner_status on weaknesses (learner_id, status);
create index if not exists idx_exercises_practice_session on exercises (practice_session_id);
create index if not exists idx_exercise_attempts_exercise on exercise_attempts (exercise_id);
create index if not exists idx_practice_sessions_learner on practice_sessions (learner_id, weakness_category);
create index if not exists idx_attempts_learner on attempts (learner_id);
