// Shared domain types for رِحلة (Rihla)

// These mirror the Postgres schema in lib/db/schema/001_init.sql

export type ArabicLevel =
  | 'Beginner'
  | 'Elementary'
  | 'Intermediate'
  | 'Upper Intermediate'
  | 'Advanced';

export type LearningGoal =
  | 'Speaking'
  | 'Writing'
  | 'Reading'
  | 'Understanding Arabic'
  | 'General Arabic';

// The three V1 core error categories, plus the escape hatch for
// anything the analyzer sees but is out of scope for V1 (spec §7).

export const CORE_CATEGORIES = [
  'حروف الجر',
  'التذكير والتأنيث',
  'المفرد والجمع',
] as const;

export type CoreCategory =
  (typeof CORE_CATEGORIES)[number];

export type ErrorCategory =
  | CoreCategory
  | 'Other';

export type WeaknessStatus =
  | 'potential'
  | 'needs_practice'
  | 'improving'
  | 'mastered';

export type Priority =
  | 'high'
  | 'medium'
  | 'low';

export type Difficulty =
  | 'easy'
  | 'moderate'
  | 'hard'
  | 'transfer';

  export type PracticeSessionType =
  | 'adaptive_practice'
  | 'maintenance_review';

export type ExerciseType =
  | 'multiple_choice'
  | 'correction'
  | 'fill_in_blank'
  | 'free_production';

export interface Learner {
  id: string;
  name: string;
  self_reported_level: ArabicLevel;
  learning_goal: LearningGoal;
  observed_level: ArabicLevel;
  strengths: string[];
  current_focus: string | null;
  created_at: string;
  updated_at: string;
}

// A diagnostic free-text writing submission.
// V1 only produces these from the onboarding diagnostic screen (§6),
// but the row shape supports future diagnostic-style prompts.

export interface Attempt {
  id: string;
  learner_id: string;
  input_text: string;
  created_at: string;
}

export interface DetectedError {
  id: string;
  learner_id: string;
  attempt_id: string;
  category: ErrorCategory;
  original_text: string;
  correction: string;
  explanation_ar: string;
  explanation_en: string;
  confidence: number; // 0..1
  created_at: string;
}

export interface Weakness {
  id: string;
  learner_id: string;
  category: CoreCategory;

  // error_count is the sum of the two sources below (DB: a
  // generated column; app: derived by recalculateWeakness).
  // Kept for the confirmation rule and existing call sites.

  error_count: number;

  // Source breakdown, kept so errors can be inspected/audited
  // by origin later.

  diagnostic_error_count: number;

  practice_error_count: number;

  attempt_count: number;

  relevant_question_count: number;

  correct_count: number;

  accuracy: number; // 0..1, derived from exercise performance only

  status: WeaknessStatus;

  priority: Priority;

  last_detected: string | null;

  created_at: string;

  updated_at: string;
}

// A batch of exactly 5 exercises generated by one adaptive decision.

export interface PracticeSession {
  id: string;

  learner_id: string;

  weakness_category: CoreCategory;

  difficulty: Difficulty;

  session_type: PracticeSessionType;

  score: number | null;

  accuracy_before: number | null;

  accuracy_after: number | null;

  created_at: string;

  completed_at: string | null;
}

export interface Exercise {
  id: string;

  learner_id: string;

  practice_session_id: string;

  weakness_category: CoreCategory;

  difficulty: Difficulty;

  exercise_type: ExerciseType;

  instruction_ar: string;

  question: string;

  options: string[] | null;

  correct_answer: string;

  explanation_ar: string;

  created_at: string;
}

export interface ExerciseAttempt {
  id: string;

  exercise_id: string;

  learner_id: string;

  answer: string;

  is_correct: boolean;

  created_at: string;
}

// ---- Maintenance review ----

export interface MaintenanceReview {
  id: string;

  learner_id: string;

  category: CoreCategory;

  review_number: number;

  total_questions: number;

  correct_count: number;

  accuracy: number;

  reactivation_signal: boolean;

  created_at: string;
}

// ---- Adaptive engine input/output ----

export interface LearnerState {
  learner: Learner;

  weaknesses: Weakness[];

  // Optional for backward compatibility with existing tests
  // and current call sites.
  maintenanceReviews?: MaintenanceReview[];
}

export type AdaptiveAction =
  | 'diagnostic_practice'
  | 'monitor'
  | 'explain_and_practice'
  | 'targeted_practice'
  | 'targeted_practice_increase_difficulty'
  | 'maintenance_review'
  | 'all_mastered';
  
export interface AdaptiveDecision {
  action: AdaptiveAction;

  category: CoreCategory | null;

  difficulty: Difficulty | null;

  status: WeaknessStatus | null;

  priority: Priority | null;

  reason: string;
}